[package]
name = "rs-tpa-analyze"
version = "0.1.0"
authors = ["Ubsefor <letzdropthebas@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
percentage = "0.1.0" 
regex = "1"